server:
  port: 8080

spring:
  profiles:
    active: local
#    active: docker
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  webflux:
    multipart:
      max-in-memory-size: 10MB
#    open-in-view: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/hygiene?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
#    url: jdbc:mysql://localhost:3307/hygiene_서울백병원?useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: admin
#    password: hasdev1234

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    username: root
#    password: "9999"
    url: jdbc:mysql://mysql:3306/hygiene?useSSL=false&useUnicode=true&characterEncoding=utf8

